// Auto-generated by scripts/extract-data.mjs from reference/app.html.
// Do not edit by hand — re-run the extractor if the source changes.
/* eslint-disable */

export interface CpmBand {
  lo: number;
  hi: number;
  med: number;
  dedMult: number;
}

export const NICHE_SPONSOR_CPM: Record<string, CpmBand> = {
  "Finance & Investing": {
    "lo": 20,
    "hi": 50,
    "med": 30,
    "dedMult": 2
  },
  "Education & Self-Development": {
    "lo": 12,
    "hi": 28,
    "med": 18,
    "dedMult": 1.8
  },
  "Tech & Gadgets": {
    "lo": 10,
    "hi": 25,
    "med": 16,
    "dedMult": 1.8
  },
  "Tech & Product Reviews": {
    "lo": 10,
    "hi": 25,
    "med": 16,
    "dedMult": 1.8
  },
  "Automotive": {
    "lo": 9,
    "hi": 22,
    "med": 14,
    "dedMult": 1.7
  },
  "Health & Fitness": {
    "lo": 8,
    "hi": 20,
    "med": 12,
    "dedMult": 1.6
  },
  "Travel & Adventure": {
    "lo": 7,
    "hi": 18,
    "med": 10,
    "dedMult": 1.6
  },
  "Beauty & Skincare": {
    "lo": 6,
    "hi": 16,
    "med": 9,
    "dedMult": 1.6
  },
  "Beauty & Fashion": {
    "lo": 6,
    "hi": 16,
    "med": 9,
    "dedMult": 1.6
  },
  "Food & Cooking": {
    "lo": 5,
    "hi": 14,
    "med": 8,
    "dedMult": 1.5
  },
  "Gaming & Esports": {
    "lo": 5,
    "hi": 15,
    "med": 8,
    "dedMult": 1.6
  },
  "Trading Cards (TCG)": {
    "lo": 7,
    "hi": 20,
    "med": 12,
    "dedMult": 1.7
  },
  "Unboxing": {
    "lo": 4,
    "hi": 12,
    "med": 7,
    "dedMult": 1.5
  },
  "Music": {
    "lo": 3,
    "hi": 10,
    "med": 6,
    "dedMult": 1.5
  },
  "Lifestyle & Vlogs": {
    "lo": 4,
    "hi": 12,
    "med": 6,
    "dedMult": 1.5
  },
  "Entertainment & Comedy": {
    "lo": 3,
    "hi": 9,
    "med": 5,
    "dedMult": 1.5
  },
  "Theatre & Performing Arts": {
    "lo": 5,
    "hi": 14,
    "med": 8,
    "dedMult": 1.6
  },
  "Gaming Setup & Peripherals": {
    "lo": 7,
    "hi": 18,
    "med": 11,
    "dedMult": 1.7
  },
  "Drinks & Beverages": {
    "lo": 4,
    "hi": 12,
    "med": 7,
    "dedMult": 1.5
  },
  "Kids & Family / Toys": {
    "lo": 4,
    "hi": 12,
    "med": 7,
    "dedMult": 1.5
  },
  "Kids & Family": {
    "lo": 4,
    "hi": 12,
    "med": 7,
    "dedMult": 1.5
  }
};

export const DEFAULT_CPM: CpmBand = {
  "lo": 5,
  "hi": 14,
  "med": 8,
  "dedMult": 1.6
};

export const PLATFORM_MULT: Record<string, number | null> = {
  "youtube": 1,
  "instagram": 0.75,
  "tiktok": 0.5,
  "twitch": null,
  "kick": 0.4,
  "x": 0.45
};
