// One-off extractor: pulls CREATORS + CPM tables out of reference/app.html
// and writes them to src/app/core/data/*.
//
// Re-run whenever app.html's CREATORS array changes:
//   node scripts/extract-data.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const SRC = 'reference/app.html';
const OUT_DIR = 'src/app/core/data';

const source = readFileSync(SRC, 'utf8');

function extract(label, pattern) {
  const m = source.match(pattern);
  if (!m) throw new Error(`Could not locate ${label} in ${SRC}`);
  return m[1];
}

const creatorsLiteral = extract('CREATORS', /const CREATORS = (\[[\s\S]*?\n\]);/);
const nicheLiteral = extract('NICHE_SPONSOR_CPM', /const NICHE_SPONSOR_CPM = (\{[\s\S]*?\n\});/);
const defaultLiteral = extract('DEFAULT_CPM', /const DEFAULT_CPM = (\{[^}]+\});/);
const platformLiteral = extract('PLATFORM_MULT', /const PLATFORM_MULT = (\{[^}]+\});/);

// Evaluate the JS literals in a controlled scope so we can re-emit as JSON.
// The literals are pure data (object/array literals with strings/numbers/null/undefined).
function evalLiteral(lit) {
  // eslint-disable-next-line no-new-func
  return new Function(`"use strict"; return (${lit});`)();
}

const creators = evalLiteral(creatorsLiteral).filter(
  (c) => c && typeof c === 'object' && typeof c.cpi === 'number',
);
const niche = evalLiteral(nicheLiteral);
const defaultCpm = evalLiteral(defaultLiteral);
const platform = evalLiteral(platformLiteral);

mkdirSync(OUT_DIR, { recursive: true });

// JSON.stringify drops `undefined` fields by default — correct for our case.
// The service imports this JSON directly and casts to Creator[].
writeFileSync(`${OUT_DIR}/creators.data.json`, JSON.stringify(creators));

const cpmOut = `// Auto-generated by scripts/extract-data.mjs from reference/app.html.
// Do not edit by hand — re-run the extractor if the source changes.
/* eslint-disable */

export interface CpmBand {
  lo: number;
  hi: number;
  med: number;
  dedMult: number;
}

export const NICHE_SPONSOR_CPM: Record<string, CpmBand> = ${JSON.stringify(niche, null, 2)};

export const DEFAULT_CPM: CpmBand = ${JSON.stringify(defaultCpm, null, 2)};

export const PLATFORM_MULT: Record<string, number | null> = ${JSON.stringify(platform, null, 2)};
`;
writeFileSync(`${OUT_DIR}/cpm-tables.data.ts`, cpmOut);

console.log(`✓ creators.data.json — ${creators.length} creators`);
console.log(`✓ cpm-tables.data.ts — ${Object.keys(niche).length} niches`);
